# Generated by Django 4.0.6 on 2022-08-05 04:03

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc
import upload_docs.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pds',
            name='tor',
            field=models.FileField(default=datetime.datetime(2022, 8, 5, 4, 3, 45, 975626, tzinfo=utc), upload_to=upload_docs.models.user_directory_path, validators=[upload_docs.models.validate_file_size, django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Transcript of Record'),
            preserve_default=False,
        ),
    ]
