# Generated by Django 4.0.6 on 2022-08-08 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_docs', '0004_alter_tor_tor_cav'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cav',
            old_name='tor',
            new_name='cav',
        ),
    ]
