# Generated by Django 4.0.6 on 2022-08-05 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rma.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('living_status', rma.models.Uppercase(choices=[('LIVING', 'LIVING'), ('DECEASED', 'DECEASED'), ('NOT KNOWN', 'NOT KNOWN')], max_length=9, verbose_name='Living Status')),
                ('last_name', rma.models.Uppercase(max_length=200, verbose_name='Last name (Maiden)')),
                ('first_name', rma.models.Uppercase(max_length=200, verbose_name='First name')),
                ('middle_name', rma.models.Uppercase(blank=True, max_length=200, verbose_name='Middle name')),
                ('suffix', rma.models.Uppercase(blank=True, choices=[('JR', 'JR'), ('SR', 'SR'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=3, verbose_name='Suffix')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6, verbose_name='Gender')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Spouse',
            },
        ),
        migrations.CreateModel(
            name='Sibling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('living_status', rma.models.Uppercase(choices=[('LIVING', 'LIVING'), ('DECEASED', 'DECEASED'), ('NOT KNOWN', 'NOT KNOWN')], max_length=9, verbose_name='Living Status')),
                ('last_name', rma.models.Uppercase(max_length=200, verbose_name='Last name (Maiden)')),
                ('first_name', rma.models.Uppercase(max_length=200, verbose_name='First name')),
                ('middle_name', rma.models.Uppercase(blank=True, max_length=200, verbose_name='Middle name')),
                ('suffix', rma.models.Uppercase(blank=True, choices=[('JR', 'JR'), ('SR', 'SR'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=3, verbose_name='Suffix')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6, verbose_name='Gender')),
                ('civil_status', rma.models.Uppercase(choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED'), ('WIDOWED', 'WIDOWED'), ('SEPARATED', 'SEPARATED'), ('DIVORCED', 'DIVORCED')], max_length=9, verbose_name='Civil status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sibling',
            },
        ),
        migrations.CreateModel(
            name='SeniorHigh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', rma.models.Uppercase(max_length=200, verbose_name='Name of School')),
                ('year_from', rma.models.Uppercase(choices=[('N/A', 'N/A'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=4, verbose_name='From')),
                ('year_to', rma.models.Uppercase(choices=[('N/A', 'N/A'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=4, verbose_name='To')),
                ('highest_level', rma.models.Uppercase(choices=[('GRADUATED', 'GRADUATED'), ('GRADE 11', 'GRADE 11'), ('GRADE 12', 'GRADE 12')], max_length=50, verbose_name='Highest Level')),
                ('year_graduated', rma.models.Uppercase(choices=[('N/A', 'N/A'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=4, verbose_name='Year Graduated')),
                ('academic_honors', rma.models.Uppercase(blank=True, max_length=150, verbose_name='Academic Honors Received')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Senior High',
            },
        ),
        migrations.CreateModel(
            name='Primary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', rma.models.Uppercase(max_length=200, verbose_name='Name of School')),
                ('year_from', rma.models.Uppercase(choices=[('N/A', 'N/A'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=4, verbose_name='From')),
                ('year_to', rma.models.Uppercase(choices=[('N/A', 'N/A'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=4, verbose_name='To')),
                ('highest_level', rma.models.Uppercase(choices=[('GRADUATED', 'GRADUATED'), ('GRADE 1', 'GRADE 1'), ('GRADE 2', 'GRADE 2'), ('GRADE 3', 'GRADE 3'), ('GRADE 4', 'GRADE 4'), ('GRADE 5', 'GRADE 5'), ('GRADE 6', 'GRADE 6')], max_length=50, verbose_name='Highest Level')),
                ('year_graduated', rma.models.Uppercase(choices=[('N/A', 'N/A'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=4, verbose_name='Year Graduated')),
                ('academic_honors', rma.models.Uppercase(blank=True, max_length=150, verbose_name='Academic Honors Received')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Primary Education',
            },
        ),
        migrations.CreateModel(
            name='PresentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', rma.models.Uppercase(max_length=10, verbose_name='Region')),
                ('zip_code', rma.models.Uppercase(max_length=4, verbose_name='Zipe code')),
                ('province', rma.models.Uppercase(max_length=50, verbose_name='Province')),
                ('city_municipality', rma.models.Uppercase(max_length=100, verbose_name='City/Municipality')),
                ('barangay', rma.models.Uppercase(max_length=50, verbose_name='Barangay')),
                ('house', rma.models.Uppercase(max_length=150, verbose_name='House/Lot/Unit No./Street/Subdivision')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Present Address',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', rma.models.Uppercase(max_length=200, verbose_name='Last name')),
                ('first_name', rma.models.Uppercase(max_length=200, verbose_name='First name')),
                ('middle_name', rma.models.Uppercase(blank=True, max_length=200, verbose_name='Middle name')),
                ('suffix', rma.models.Uppercase(blank=True, choices=[('JR', 'JR'), ('SR', 'SR'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=3, verbose_name='Suffix')),
                ('gender', rma.models.Uppercase(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6, verbose_name='Gender')),
                ('civil_status', models.CharField(choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED'), ('WIDOWED', 'WIDOWED'), ('SEPARATED', 'SEPARATED'), ('DIVORCED', 'DIVORCED')], max_length=9, verbose_name='Civil status')),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', rma.models.Uppercase(max_length=200, verbose_name='Place of birth')),
                ('cellphone_no', models.CharField(max_length=11, verbose_name='Cellphone Number')),
                ('height', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Height (m)')),
                ('weight', models.CharField(max_length=3, verbose_name='Weight (kg)')),
                ('blood_type', rma.models.Uppercase(blank=True, max_length=3, verbose_name='Blood type')),
                ('tin', models.CharField(blank=True, max_length=11, verbose_name='TIN')),
                ('pag_ibig', models.CharField(blank=True, max_length=20, verbose_name='Pag-ibig No.')),
                ('philhealth', models.CharField(blank=True, max_length=14, verbose_name='Philhealth No.')),
                ('sss', models.CharField(blank=True, max_length=12, verbose_name='SSS No.')),
                ('gsis', models.CharField(blank=True, max_length=15, verbose_name='GSIS/BP No.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Personal Information',
            },
        ),
        migrations.CreateModel(
            name='PermanentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', rma.models.Uppercase(max_length=10, verbose_name='Region')),
                ('zip_code', rma.models.Uppercase(max_length=4, verbose_name='Zipe code')),
                ('province', rma.models.Uppercase(max_length=50, verbose_name='Province')),
                ('city_municipality', rma.models.Uppercase(max_length=100, verbose_name='City/Municipality')),
                ('barangay', rma.models.Uppercase(max_length=50, verbose_name='Barangay')),
                ('house', rma.models.Uppercase(max_length=150, verbose_name='House/Lot/Unit No./Street/Subdivision')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Permanent Address',
            },
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('living_status', rma.models.Uppercase(choices=[('LIVING', 'LIVING'), ('DECEASED', 'DECEASED'), ('NOT KNOWN', 'NOT KNOWN')], max_length=9, verbose_name='Living Status')),
                ('last_name', rma.models.Uppercase(max_length=200, verbose_name='Last name (Maiden)')),
                ('first_name', rma.models.Uppercase(max_length=200, verbose_name='First name')),
                ('middle_name', rma.models.Uppercase(blank=True, max_length=200, verbose_name='Middle name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mother',
            },
        ),
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', rma.models.Uppercase(max_length=200, verbose_name='Name of School')),
                ('year_from', rma.models.Uppercase(choices=[('N/A', 'N/A'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=4, verbose_name='From')),
                ('year_to', rma.models.Uppercase(choices=[('N/A', 'N/A'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=4, verbose_name='To')),
                ('highest_level', rma.models.Uppercase(choices=[('GRADUATED', 'GRADUATED'), ('GRADE 7', 'GRADE 7'), ('GRADE 8', 'GRADE 8'), ('GRADE 9', 'GRADE 9'), ('GRADE 10', 'GRADE 10')], max_length=50, verbose_name='Highest Level')),
                ('year_graduated', rma.models.Uppercase(choices=[('N/A', 'N/A'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=4, verbose_name='Year Graduated')),
                ('academic_honors', rma.models.Uppercase(blank=True, max_length=150, verbose_name='Academic Honors Received')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'High School',
            },
        ),
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', rma.models.Uppercase(max_length=200, verbose_name='Name of School')),
                ('degree', rma.models.Uppercase(max_length=200, verbose_name='Degree')),
                ('year_from', rma.models.Uppercase(choices=[('N/A', 'N/A'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=4, verbose_name='From')),
                ('year_to', rma.models.Uppercase(choices=[('N/A', 'N/A'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=4, verbose_name='To')),
                ('units_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Units Earned')),
                ('year_graduated', rma.models.Uppercase(choices=[('N/A', 'N/A'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=4, verbose_name='Year Graduated')),
                ('academic_honors', rma.models.Uppercase(blank=True, max_length=150, verbose_name='Academic Honors Received')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Graduate Studies',
            },
        ),
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('living_status', rma.models.Uppercase(choices=[('LIVING', 'LIVING'), ('DECEASED', 'DECEASED'), ('NOT KNOWN', 'NOT KNOWN')], max_length=9, verbose_name='Living Status')),
                ('last_name', rma.models.Uppercase(max_length=200, verbose_name='Last name')),
                ('first_name', rma.models.Uppercase(max_length=200, verbose_name='First name')),
                ('middle_name', rma.models.Uppercase(blank=True, max_length=200, verbose_name='Middle name')),
                ('suffix', rma.models.Uppercase(blank=True, choices=[('JR', 'JR'), ('SR', 'SR'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=3, verbose_name='Suffix')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Father',
            },
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility', rma.models.Uppercase(max_length=200, verbose_name='Eligibility')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Units Earned')),
                ('date_of_exam', models.DateField(verbose_name='Date of Examination/Conferment')),
                ('place_of_exam', rma.models.Uppercase(max_length=200, verbose_name='Place of Examination/Conferment')),
                ('license', rma.models.Uppercase(blank=True, max_length=50, verbose_name='License Number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Eligibility',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', rma.models.Uppercase(max_length=200, verbose_name='Name of School')),
                ('course', rma.models.Uppercase(max_length=200, verbose_name='Course/Degree')),
                ('year_from', rma.models.Uppercase(choices=[('N/A', 'N/A'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=4, verbose_name='From')),
                ('year_to', rma.models.Uppercase(choices=[('N/A', 'N/A'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=4, verbose_name='To')),
                ('units_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Units Earned')),
                ('year_graduated', rma.models.Uppercase(choices=[('N/A', 'N/A'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=4, verbose_name='Year Graduated')),
                ('academic_honors', rma.models.Uppercase(blank=True, max_length=150, verbose_name='Academic Honors Received')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'College',
            },
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('living_status', rma.models.Uppercase(choices=[('LIVING', 'LIVING'), ('DECEASED', 'DECEASED'), ('NOT KNOWN', 'NOT KNOWN')], max_length=9, verbose_name='Living Status')),
                ('last_name', rma.models.Uppercase(max_length=200, verbose_name='Last name (Maiden)')),
                ('first_name', rma.models.Uppercase(max_length=200, verbose_name='First name')),
                ('middle_name', rma.models.Uppercase(blank=True, max_length=200, verbose_name='Middle name')),
                ('suffix', rma.models.Uppercase(blank=True, choices=[('JR', 'JR'), ('SR', 'SR'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=3, verbose_name='Suffix')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6, verbose_name='Gender')),
                ('date_of_birth', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Children',
            },
        ),
    ]
