# Generated by Django 4.0.6 on 2022-08-01 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=10, verbose_name='Region')),
                ('zip_code', models.CharField(max_length=4, verbose_name='Zipe code')),
                ('province', models.CharField(max_length=50, verbose_name='Province')),
                ('city_municipality', models.CharField(max_length=100, verbose_name='City/Municipality')),
                ('barangay', models.CharField(max_length=50, verbose_name='Barangay')),
                ('house', models.CharField(max_length=150, verbose_name='House/Lot/Unit No./Street/Subdivision')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Present Address',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last name')),
                ('first_name', models.CharField(max_length=200, verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, max_length=200, verbose_name='Middle name')),
                ('suffix', models.CharField(blank=True, choices=[('JR', 'JR'), ('SR', 'SR'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=3, verbose_name='Suffix')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6, verbose_name='Gender')),
                ('civil_status', models.CharField(choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED'), ('WIDOWED', 'WIDOWED'), ('SEPARATED', 'SEPARATED'), ('DIVORCED', 'DIVORCED')], max_length=9, verbose_name='Civil status')),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=200, verbose_name='Place of birth')),
                ('cellphone_no', models.CharField(max_length=12, verbose_name='Cellphone Number')),
                ('height', models.CharField(max_length=3, verbose_name='Height (m)')),
                ('weight', models.CharField(max_length=3, verbose_name='Weight (kg)')),
                ('blood_type', models.CharField(blank=True, max_length=3, verbose_name='Blood type')),
                ('tin', models.CharField(blank=True, max_length=11, verbose_name='TIN')),
                ('pag_ibig', models.CharField(blank=True, max_length=20, verbose_name='Pag-ibig No.')),
                ('philhealth', models.CharField(blank=True, max_length=14, verbose_name='Philhealth No.')),
                ('sss', models.CharField(blank=True, max_length=12, verbose_name='SSS No.')),
                ('gsis', models.CharField(blank=True, max_length=15, verbose_name='GSIS/BP No.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Personal Information',
            },
        ),
    ]
