# Generated by Django 4.0.6 on 2022-08-05 03:49

from django.db import migrations, models
import rma.models


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibility',
            name='place_of_exam',
            field=rma.models.Uppercase(blank=True, max_length=200, verbose_name='Place of Examination/Conferment'),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Units Earned'),
        ),
    ]
