# Generated by Django 4.0.6 on 2022-08-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
