# Generated by Django 4.0.6 on 2022-08-01 07:12

from django.db import migrations
import rma.models


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='blood_type',
            field=rma.models.Uppercase(blank=True, max_length=3, verbose_name='Blood type'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='first_name',
            field=rma.models.Uppercase(max_length=200, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='last_name',
            field=rma.models.Uppercase(max_length=200, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='middle_name',
            field=rma.models.Uppercase(blank=True, max_length=200, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='place_of_birth',
            field=rma.models.Uppercase(max_length=200, verbose_name='Place of birth'),
        ),
    ]
