# Generated by Django 4.0.6 on 2022-08-02 01:02

from django.db import migrations
import rma.models


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0002_alter_personalinfo_blood_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentaddress',
            name='barangay',
            field=rma.models.Uppercase(max_length=50, verbose_name='Barangay'),
        ),
        migrations.AlterField(
            model_name='presentaddress',
            name='city_municipality',
            field=rma.models.Uppercase(max_length=100, verbose_name='City/Municipality'),
        ),
        migrations.AlterField(
            model_name='presentaddress',
            name='house',
            field=rma.models.Uppercase(max_length=150, verbose_name='House/Lot/Unit No./Street/Subdivision'),
        ),
        migrations.AlterField(
            model_name='presentaddress',
            name='province',
            field=rma.models.Uppercase(max_length=50, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='presentaddress',
            name='region',
            field=rma.models.Uppercase(max_length=10, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='presentaddress',
            name='zip_code',
            field=rma.models.Uppercase(max_length=4, verbose_name='Zipe code'),
        ),
    ]
