# Generated by Django 4.0.6 on 2022-08-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0002_quota_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Close', max_length=5, verbose_name='Status'),
        ),
    ]
