# Generated by Django 4.0.6 on 2022-08-03 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rma.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rma', '0002_alter_sibling_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('living_status', rma.models.Uppercase(choices=[('LIVING', 'LIVING'), ('DECEASED', 'DECEASED'), ('NOT KNOWN', 'NOT KNOWN')], max_length=9, verbose_name='Living Status')),
                ('last_name', rma.models.Uppercase(max_length=200, verbose_name='Last name (Maiden)')),
                ('first_name', rma.models.Uppercase(max_length=200, verbose_name='First name')),
                ('middle_name', rma.models.Uppercase(blank=True, max_length=200, verbose_name='Middle name')),
                ('suffix', rma.models.Uppercase(blank=True, choices=[('JR', 'JR'), ('SR', 'SR'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=3, verbose_name='Suffix')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6, verbose_name='Gender')),
                ('date_of_birth', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Children',
            },
        ),
    ]
