# Generated by Django 4.0.6 on 2022-08-02 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rma.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rma', '0003_alter_presentaddress_barangay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', rma.models.Uppercase(max_length=10, verbose_name='Region')),
                ('zip_code', rma.models.Uppercase(max_length=4, verbose_name='Zipe code')),
                ('province', rma.models.Uppercase(max_length=50, verbose_name='Province')),
                ('city_municipality', rma.models.Uppercase(max_length=100, verbose_name='City/Municipality')),
                ('barangay', rma.models.Uppercase(max_length=50, verbose_name='Barangay')),
                ('house', rma.models.Uppercase(max_length=150, verbose_name='House/Lot/Unit No./Street/Subdivision')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Permanent Address',
            },
        ),
    ]
