# Generated by Django 4.0.6 on 2022-08-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0004_permanentaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='cellphone_no',
            field=models.CharField(max_length=11, verbose_name='Cellphone Number'),
        ),
    ]
