# Generated by Django 4.0.6 on 2022-08-09 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0007_alter_quota_hiring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='hiring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rma.hiring'),
        ),
    ]
