# Generated by Django 4.0.6 on 2022-08-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0007_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='units_earned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, verbose_name='Units Earned'),
        ),
    ]
