# Generated by Django 4.0.6 on 2022-08-02 09:10

from django.db import migrations
import rma.models


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0010_father'),
    ]

    operations = [
        migrations.AlterField(
            model_name='father',
            name='suffix',
            field=rma.models.Uppercase(blank=True, choices=[('JR', 'JR'), ('SR', 'SR'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=3, verbose_name='Suffix'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='gender',
            field=rma.models.Uppercase(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='suffix',
            field=rma.models.Uppercase(blank=True, choices=[('JR', 'JR'), ('SR', 'SR'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=3, verbose_name='Suffix'),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='suffix',
            field=rma.models.Uppercase(blank=True, choices=[('JR', 'JR'), ('SR', 'SR'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=3, verbose_name='Suffix'),
        ),
    ]
