# Generated by Django 4.0.6 on 2022-08-02 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rma.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rma', '0011_alter_father_suffix_alter_personalinfo_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spouse',
            name='last_name',
            field=rma.models.Uppercase(max_length=200, verbose_name='Last name (Maiden)'),
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('living_status', rma.models.Uppercase(choices=[('LIVING', 'LIVING'), ('DECEASED', 'DECEASED'), ('NOT KNOWN', 'NOT KNOWN')], max_length=9, verbose_name='Living Status')),
                ('last_name', rma.models.Uppercase(max_length=200, verbose_name='Last name (Maiden)')),
                ('first_name', rma.models.Uppercase(max_length=200, verbose_name='First name')),
                ('middle_name', rma.models.Uppercase(blank=True, max_length=200, verbose_name='Middle name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mother',
            },
        ),
    ]
