# Generated by Django 4.0.6 on 2022-08-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0001_initial'),
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='batch',
        ),
        migrations.AddField(
            model_name='user',
            name='batch',
            field=models.ManyToManyField(blank=True, null=True, to='rma.quota'),
        ),
    ]
