# Generated by Django 4.0.6 on 2022-08-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0003_alter_quota_status'),
        ('authentication', '0003_remove_user_batch_user_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='batch',
            field=models.ManyToManyField(to='rma.quota'),
        ),
    ]
