# Generated by Django 4.0.6 on 2022-08-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0003_alter_quota_status'),
        ('authentication', '0005_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='batch',
            field=models.ManyToManyField(blank=True, null=True, to='rma.quota'),
        ),
    ]
