# Generated by Django 4.0.6 on 2022-08-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0004_alter_college_user'),
        ('authentication', '0007_alter_user_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='batch',
            field=models.ManyToManyField(blank=True, to='rma.quota'),
        ),
    ]
