# Generated by Django 4.0.6 on 2022-08-17 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0007_alter_college_user'),
        ('authentication', '0008_alter_user_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_rel', to='rma.college'),
        ),
    ]
