# Generated by Django 4.0.6 on 2022-08-17 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_college_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='college_field',
        ),
    ]
